// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucgeyklejttuvuqlxrco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZ2V5a2xlanR0dXZ1cWx4cmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODUyNDgsImV4cCI6MjA3MjY2MTI0OH0.6SJz6MVYluAKZIezMReL5nlnoZrlaAuoiDYLtYOMS6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});